### ISSUE TITLE
How to set RepositoryFolder as environmental variable in docker-compose

### ISSUE THREAD

**Issue by T-6** [duracellko/planningpoker4azure#134]
Could you give me a hint how to do it correctly?

My docker-compose:
`services:
  planningpoker:
    image: duracellko/planningpoker
    container_name: planningpoker
    network_mode: host
    environment:
      RepositoryFolder: "/planningpoker"
    user: "1002:100"
    restart: unless-stopped
`
Thanks a lot for your support!!!

**Comment by duracellko** [comment]
You have to specify full name of environment variable:

```yaml
services:
  planningpoker:
    environment:
    - PlanningPoker__RepositoryForlder: /planningpoker
```

Explanation: https://learn.microsoft.com/en-us/aspnet/core/fundamentals/configuration/?view=aspnetcore-7.0#non-prefixed-environment-variables

Btw, when you specify repository like this, probably it would fail, because `/planningpoker` directory does not exist in the container. Also there is no need to store data in the container.
The goal of repository was to store data outside of the container, so that when the container is restarted, the data are not lost. For that you would need to define a volume, map it in the container and use that for repository.

I found this that describes how to define volumes in docker compose: https://github.com/compose-spec/compose-spec/blob/master/spec.md

**Comment by T-6** [comment]
Thanks for your answer.
I use several container with bind mounts (volumes). 
In which file / folder are the data stored that should be stored between restarts? Then I can bind mount this folder to a folder on the host.
Thanks

**Comment by duracellko** [comment]
It would be the same folder that you configure in the environment variable. For example:
```yaml
services:
  planningpoker:
    environment:
    - PlanningPoker__RepositoryForlder: /planningpoker
    volumes:
    - /host/planningpoker/data:/planningpoker
```

`/host/planningpoker/data` should be directory. Then each team is stored as separate file there.
